### ISSUE TITLE
Account blocked due to high web request activity

### ISSUE THREAD

**Issue by CodeDuet** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#1]
Hi,
The application works great! Thank you very much for the development. However, I did experience an external issue with the PS service temporarily blocking my account due to "high activity" (they said too many web request within 10 -30 seconds time frame over an extended amount of time triggered the automated security system). Therefore, I made a small change in the code to slow down the "Download all modules" feature - which I set to download each module every couple minutes instead of all at once. Therefore, I recommend adding code to give the option of throttling the downloads. 

Changed the following function in the Coursectrl.js file:
   function downloadModuleClips(module) {
            _.forEach(module.clips, function (clip, clipIndex) {
                //Pause before each download               
                $timeout(function () {
                    setTimeout(function () {
                        vm.downloadClip(clip, module);                                            
                    }, clipIndex * 60 + '000');
                }, clipIndex * 60 + '000');
               
            });
        }

**Comment by tutoriel** [comment]
Hi,
also my account is blocked my question is the function that you have writing fix the problem ?

**Comment by Ebram-Tharwat** [comment]
@CodeDuet , I apologize for my very late response.

I'm glad that you found the application helpful to you. I have encountered this issue today myself and you were right.
Your fix code works fine, except it would take time while downloading videos. So, maybe it should be less than 60 seconds.
I have changed the `downloadClip` function so that it accept an argument to determine if it should download the next video clips or not. If true, it will continue normally to download the next clip after 3 seconds of delay.

@tutoriel , please update the application and try it with this fix.

Your feedback is highly appreciated and suggestions are very welcomed.
