### ISSUE TITLE
Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by ancgate** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#3]
This is an excellent work. Thank very much Ebram. Unfortunately I got this message, when the apps start to download the seconde module for any courses
"object reference not set to an instance of an object ".

**Comment by Ebram-Tharwat** [comment]
@ancgate , can you please provide more info like:

- Link of the course you were trying to download.
- Did you have connectoin problem?
- Have you tried again? or Have you tried to debug the error?

**Comment by ancgate** [comment]
1) Link : design-patterns-java-behavioral
2) Don't have any connection problem
3) Exception thrown: 'System.NullReferenceException' in PluralsightDownloader.Web.dll

**Comment by Ebram-Tharwat** [comment]
@ancgate , I checked the course then tried to download it, and it works fine. So, I believe you are facing this issue due to invalid provided credentials.

Thus, I have pushed a commit, to display a descriptive error message when trying to get authentication cookie with invalid credentials.

@ancgate, could you please check that you have the correct credentials, and if not, make sure you are getting a clear error message? So that I could close this issue.

**Comment by ancgate** [comment]
You are right. It was due to invalid credentials. It is working now. Thanks again.
