### ISSUE TITLE
Account lock prevention

### ISSUE THREAD

**Issue by brunnels** [Ebram-Tharwat/CSharp-Pluralsight-Downloader#4]
I guess pluralsight must have changed something to be more strict because I got account locked pretty quickly after queuing up a couple of courses.  I've modified the CourseController a little to add a ThrottledStream class I found on CodeProject.  I'm using the clip duration and the totalbytes to throttle the download to take as long as the clip duration.  

I know this is slow but who really cares as long as you can queue up a whole course and come back in a while and it's done without worrying about locking your account?

That being said, with this change it would be nicer to keep the queue server side so it can be processed in the background.  In addition to that there should be a queue page to see what's in the queue and have history of what was already downloaded.

**Comment by Ebram-Tharwat** [comment]
@brunnels , thank you much for your feedback.

I have checked some other projects for downloading from Pluralsight, and they have the same problem. According to users' comments, setting delay of 120 seconds between each video should prevent account locking(check [https://github.com/rg3/youtube-dl/issues/6090](url) ).

Still, I like the idea of your fix and I would appreciate if you could share your code.

Regarding your suggestions:

1. Why do you prefer to process the queue server-side? Doing it on the client-side does not block the server, also, I see it much easier and keep the server focusing on the downloading task.

1. For the queue page, how do you see it should look like? Should it be a history of what have been downloaded(or as a log file preview), or just displaying which videos are currently in the queue.

**Comment by brunnels** [comment]
I'll send a pull request soon.  I'm finding that downloading at 4x speed hasn't produced any locks yet.  

I'm still working on a couple changes to the file and folder naming to add leading zeros so sorting will work correctly.  I'm also adding in something to download the course files and transcripts.  

It should also be possible to create srt subtitle files.  I just need to work out the file format.

I would prefer the queue server side so it's possible to queue multiple courses and see the progress of each,  This is pretty essential with the addition of the download speed limitations so you don't need to leave the browser window open and computer running until the course has completed downloading.

As far as the layout I would have a single page with the name of each course in the queue and a progress bar with total clip count vs clips downloaded and also clips queued.  When you click the course then it brings up the current page that displays the course information and allows queuing of clips. 

 I would also add an "add course" button to the queue page that brings up a window to enter the course url and add to the queue rather than the current box to enter course description and button to download course information.

**Comment by brunnels** [comment]
I have to make a fork and submit a PR but I was able to work on it a little bit today.

- I have the file naming fixes in place
- I added the classes for the transcripts and am serializing the json responses.  Just have to figure out how to display them because they're essentially just the captions.
- I added the course files url to the Course object
- I made the video download speed multiplier configurable in web.config
- I modified the clipUrl to download 1280x720 to eliminate the black bars
- I modified the clipUrl to include the captions, just need to figure out how to turn them into SRT files
- I added a ffmpeg nuget package to re-encode the files to be smaller if desired.  I originally did it to get rid of the black bars before I realized I could modify the getUrl so not sure it's really needed but it's neat none the less

**Comment by Ebram-Tharwat** [comment]
@brunnels , that's wonderful to hear, really appreciate your help and time.

What I were currently working on lately:

- Update packages, add [angularjs ui router](https://github.com/angular-ui/ui-router) for handling routers, add [ninject](http://www.ninject.org/) for handling dependencies.
- Settings page, so user can easily modify the "download settings/configurations", and save these settings in `.json` file instead of `web.config`.
- Add "download subtitles" feature, you just need to set `cap = true` and parse the JSON result , but I guess you already figured that out. 

Regarding your suggestions:

- How to display captions? I think we need to create `.sub` or `.srt` file, and then any video player will display these captions (like any normal movie subtitle).
- Regarding the SRT file format, check out this nodejs package [subtitles-parser](https://www.npmjs.com/package/subtitles-parser). It's pretty simple, so I was going to make a C# version of it. Let me know what you think of that.
- For video quality, I think this should be included in the configuration or selected from a dropdownlist in a settings page.
- For `ffmpeg`, we can use it to convert videos to any format that user want, compressing videos, or any video manipulation; if required.
- I didn't get your meaning by "file naming fixes in place" !

Finally, let me know how I can help you with your changes(at least with subtitle feature). Also, do you think I should add a "development" branch so that we both can work on it, or wait till you finish your changes? For the current moment, I will hold off my changes.

**Comment by amgadfahmi** [comment]
@brunnels  Thanks for this change, i got a clone from ur repo and works perfectly 
@Ebram-Tharwat  i think you should think seriously about merging this PR after reviewing

**Comment by Ebram-Tharwat** [comment]
@amgadfahmi, Currently, some of my friends are trying this PR and once tested, i will merge it. Thank you again for feedback and testing.
